### ISSUE TITLE
Please git tag the last two releases

### ISSUE THREAD

**Issue by kasimon** [noris-network/puppet-exim#25]
Hi,

our internal module management workflow depends on the version tags in the git repo. For the last two releases, these tags are missing (v0.2.7, v0.2.8). Could you please add these?

**Comment by jvetter83** [comment]
Hi kasimon,

sorry for the late reply. The tags have been added. i'll close this issue.

kind regards,

jochen

**Comment by kasimon** [comment]
Awesome, thanks a lot!
