### ISSUE TITLE
`require_files` should join array items

### ISSUE THREAD

**Issue by maxenced** [noris-network/puppet-exim#51]
`require_files` is defined as [`Optional[Array[String]]`](https://github.com/noris-network/puppet-exim/blob/master/manifests/router.pp#L179) but values are not joined in [template](https://github.com/noris-network/puppet-exim/blob/1203503f96b007233104aa1698dfd3f618d7adf5/templates/router/router.erb#L111).

This causes a `require_files = ['file1', 'file2']` in exim config, which finally leads to a "['file1', 'file2'] is not absolute".

**Comment by mleiner** [comment]
Thank you! We're on it.

**Comment by mleiner** [comment]
We have released version 1.1.1 on forge.

**Comment by maxenced** [comment]
so fast, thanks !
