### ISSUE TITLE
Rename data/os/Redhat.yaml to data/os/RedHat.yaml

### ISSUE THREAD

**Issue by dakine1111** [noris-network/puppet-exim#55]
Please rename Redhat.yaml to RedHat.yaml.
Otherwise I'm getting:

`Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Exim]: parameter 'config_path' expects a String value, got Undef`

**Comment by mleiner** [comment]
Thank you for pointing this out! This will be fixed in the next release.

**Comment by mleiner** [comment]
I currently cannot continue to work on this issue because of puppet lagging behind ubuntu releases (especially ruby 3), see https://github.com/puppetlabs/puppet-module-gems/issues/166

**Comment by mleiner** [comment]
I managed to get things working again, see commit 5de4d7f917efdb4e72bbe294fa655f773eb06ab2 for the ugly details.

I have released versions 1.1.8 and 1.2.0 which both contain the fix and introduce support for RockyLinux too.
