### ISSUE TITLE
incomplete release 1.3.3 

### ISSUE THREAD

**Issue by moritzfriedrich** [noris-network/puppet-exim#60]
Somehow the changes were lost when the tag was created.
At least the release does not contain the specified change.

**Comment by mleiner** [comment]
The tag contains the change:
https://github.com/noris-network/puppet-exim/compare/v1.3.2...v1.3.3

I'll have to check with puppet forge.

**Comment by moritzfriedrich** [comment]
Thank you for your quick response. Works as desired :)
